use_frameworks!

target 'WTAuthorizationTool_Example' do
  pod 'WTAuthorizationTool', :path => '../'

  target 'WTAuthorizationTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
